plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
twitter:
  username: avivl
  card: summary
url: 'https://doitintl.github.io/bigquery-grafana/' # Site url, also used in jekyll-seo-tag
repo: 'https://github.com/doitintl/bigquery-grafana/'

show_downloads: true
title: BigQuery Grafana Datasource
description: BigQuery Grafana datasource plugin provide support for BigQuery as a backend database.
google_analytics: UA-137158105-1
theme: jekyll-theme-midnight
